use_frameworks!

target 'LTStyle_Example' do
  pod 'LTStyle', :path => '../'

  target 'LTStyle_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
